const STORAGE_KEY = "storia-sguardo-06-state";
const clone = value => JSON.parse(JSON.stringify(value));
const defaultState = {
  initialNote:"", finalNote:"", visited:[], structureLevels:[], light:"",
  region:"france", comparison:{building:"roman",category:""},
  quiz:{index:0,direct:0,errors:[],recoveries:[],completed:false,answeredCorrect:false,pendingRecovery:false,recoveryPassed:false}
};

function loadState(){
  try{
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");
    return {...defaultState,...saved,visited:Array.isArray(saved.visited)?saved.visited:[],structureLevels:Array.isArray(saved.structureLevels)?saved.structureLevels:[],comparison:{...defaultState.comparison,...(saved.comparison||{})},quiz:{...defaultState.quiz,...(saved.quiz||{})}};
  }catch(_){return clone(defaultState)}
}
let state=loadState();
const saveState=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));

// Taccuino iniziale e rilettura finale.
const initialNote=document.querySelector("#initial-note");
const finalNote=document.querySelector("#final-note");
const initialMemory=document.querySelector("#initial-memory");
initialNote.value=state.initialNote;finalNote.value=state.finalNote;
function updateMemory(){initialMemory.textContent=state.initialNote.trim()||"Non hai ancora salvato la prima osservazione."}
updateMemory();
document.querySelectorAll(".save-note").forEach(button=>button.addEventListener("click",()=>{
  const field=document.querySelector(`#${button.dataset.note}`);
  const key=button.dataset.note==="initial-note"?"initialNote":"finalNote";
  const status=document.querySelector(key==="initialNote"?"#initial-status":"#final-status");
  state[key]=field.value.trim();saveState();updateMemory();status.textContent=state[key]?"Salvato localmente.":"Nota vuota: salvataggio rimosso.";
}));
document.querySelectorAll(".opening-questions button").forEach(button=>button.addEventListener("click",()=>{
  const seed=`${button.textContent} `;
  if(!initialNote.value.includes(seed))initialNote.value+=`${initialNote.value.trim()?"\n":""}${seed}`;
  initialNote.focus();
}));

// Avanzamento della lettura e indice.
const progressBar=document.querySelector("#progress-bar");
const journeyState=document.querySelector("#journey-state");
const tracked=[...document.querySelectorAll(".tracked")];
function updateJourney(){journeyState.textContent=`${state.visited.length} / ${tracked.length} tappe`}
updateJourney();
if("IntersectionObserver" in window){
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
    if(!entry.isIntersecting||entry.intersectionRatio<.18)return;
    const label=entry.target.dataset.track;
    if(!state.visited.includes(label)){state.visited.push(label);saveState();updateJourney()}
  }),{threshold:[.18,.45]});
  tracked.forEach(section=>observer.observe(section));
}
function updateReadProgress(){const max=document.documentElement.scrollHeight-innerHeight;progressBar.style.width=`${max>0?Math.min(100,Math.max(0,scrollY/max*100)):0}%`}
addEventListener("scroll",updateReadProgress,{passive:true});addEventListener("resize",updateReadProgress);updateReadProgress();
const nav=document.querySelector("#chapter-nav");const navToggle=document.querySelector("#nav-toggle");const navClose=document.querySelector("#nav-close");let navReturnFocus=null;
function openNav(){navReturnFocus=document.activeElement;nav.hidden=false;navToggle.setAttribute("aria-expanded","true");document.body.classList.add("nav-open");navClose.focus()}
function closeNav(){nav.hidden=true;navToggle.setAttribute("aria-expanded","false");document.body.classList.remove("nav-open");navReturnFocus?.focus()}
navToggle.addEventListener("click",openNav);navClose.addEventListener("click",closeNav);nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",closeNav));

// Interazione principale: Solleva la città.
const structureOrder=["pillar","arch","rib","buttress","flying","clerestory","glass"];
const structureData={
  pillar:{name:"Pilastro composto",see:"Un nucleo con colonnine addossate sale senza interrompersi verso gli archi.",does:"Raccoglie carichi verticali e parte delle spinte trasmesse da archi e costoloni.",space:"Rende leggibile l’ossatura e scandisce la navata in campate.",social:"Richiede pietra selezionata, taglio preciso, fondazioni, scalpellini e coordinamento del cantiere."},
  arch:{name:"Arco acuto",see:"Due curve si incontrano in una cuspide sopra la campata.",does:"Permette di coprire luci diverse mantenendo quote di chiave compatibili; indirizza i carichi verso i sostegni.",space:"Accentua la direzione verticale e rende più flessibile la geometria delle campate.",social:"Non è un’invenzione isolata del Gotico: presuppone circolazione di forme e capacità di tracciamento."},
  rib:{name:"Volta costolonata",see:"Costoloni diagonali e trasversali definiscono lo scheletro della volta.",does:"Concentrano e guidano una parte dei carichi verso punti determinati; le vele completano la copertura.",space:"La copertura appare articolata in linee e campate invece che come massa continua.",social:"Richiede centine lignee, carpentieri, geometria di cantiere e sequenze di montaggio controllate."},
  buttress:{name:"Contrafforte",see:"Un grande sostegno esterno si addossa al perimetro.",does:"Oppone massa alle spinte laterali e le conduce verso il terreno.",space:"Libera l’interno da parte dell’ingombro necessario a resistere alle spinte.",social:"Occupa suolo urbano, consuma materiale e implica controllo delle aree attorno alla chiesa."},
  flying:{name:"Arco rampante",see:"Un arco esterno scavalca la copertura laterale e raggiunge il contrafforte.",does:"Trasferisce spinte delle volte alte verso sostegni esterni; non elimina il peso.",space:"Permette di alleggerire tratti della parete superiore e aumentare le aperture.",social:"Richiede calcolo empirico, manutenzione, ponteggi e una scala economica che renda sostenibile lo scheletro esterno."},
  clerestory:{name:"Cleristorio",see:"La fascia alta della navata si apre fra i sostegni.",does:"Occupa una zona resa meno massiccia dalla redistribuzione delle spinte.",space:"Porta luce sopra le navate laterali e modifica il rapporto fra parete e altezza.",social:"Presuppone vetrai, serramenti, protezione dalle intemperie e manutenzione continua."},
  glass:{name:"Vetrata",see:"Frammenti colorati e piombi trasformano l’apertura in immagine.",does:"Chiude la finestra senza svolgere la funzione portante principale della muratura.",space:"Filtra la luce, costruisce ritmo cromatico e rende la parete percettivamente attraversabile.",social:"Richiede fornaci, pigmenti, piombo, iconografi, donatori e botteghe specializzate."}
};
state.structureLevels=structureOrder.slice(0,Math.max(0,Math.min(structureOrder.length,state.structureLevels.filter((part,index)=>part===structureOrder[index]).length)));
const partReading=document.querySelector("#part-reading");const partProgress=document.querySelector("#part-progress");const stageStatus=document.querySelector("#stage-status");
function showPart(part){const d=structureData[part];partReading.innerHTML=`<p><b>Che cosa vedo</b><br>${d.see}</p><p><b>Che cosa fa strutturalmente</b><br>${d.does}</p><p><b>Che cosa rende possibile nello spazio</b><br>${d.space}</p><p><b>Quale condizione sociale e materiale richiede</b><br>${d.social}</p>`;stageStatus.textContent=`${d.name}: il sistema ora comprende ${state.structureLevels.length} elementi su ${structureOrder.length}.`}
function renderStructure(){
  const unlocked=Math.min(structureOrder.length,state.structureLevels.length+1);
  structureOrder.forEach((part,index)=>{
    const active=state.structureLevels.includes(part);const button=document.querySelector(`[data-part-button="${part}"]`);button.disabled=index>=unlocked;button.setAttribute("aria-pressed",String(active));document.querySelector(`[data-part="${part}"]`)?.classList.toggle("is-active",active);
  });
  document.querySelector('[data-part="forces"]').classList.toggle("is-active",state.structureLevels.length>=3);
  partProgress.textContent=`${state.structureLevels.length} / ${structureOrder.length} elementi attivati`;
  if(state.structureLevels.length)showPart(state.structureLevels.at(-1));
}
document.querySelectorAll("[data-part-button]").forEach(button=>button.addEventListener("click",()=>{
  const part=button.dataset.partButton;const index=structureOrder.indexOf(part);
  if(index>state.structureLevels.length)return;
  if(!state.structureLevels.includes(part))state.structureLevels.push(part);
  saveState();renderStructure();showPart(part);
}));renderStructure();

// Strati materiali della vetrata.
const lightTexts={glass:"Silice, fondenti e ossidi producono vetri colorati nella massa. Spessore e irregolarità modificano la trasmissione luminosa.",pigment:"Grisaille e pittura aggiungono linee, ombre e dettagli. La luce attraversa un’immagine dipinta e cotta.",lead:"Il piombo unisce i frammenti e diventa disegno visibile. Non è un difetto da ignorare, ma parte della struttura dell’immagine.",distance:"Dal pavimento i pannelli alti non si leggono come pagine vicine: scala, posizione e luce selezionano ciò che il corpo può vedere.",patron:"Vescovi, capitoli, sovrani, nobili e mestieri finanziano finestre; donatori e lavori possono entrare nelle scene.",rite:"Canto, processioni, calendario e orientamento attivano la vetrata nel tempo: la stessa finestra non appare sempre uguale."};
const lightFeedback=document.querySelector("#light-feedback");
document.querySelectorAll("[data-light]").forEach(button=>{
  const active=state.light===button.dataset.light;button.setAttribute("aria-pressed",String(active));if(active)lightFeedback.textContent=lightTexts[state.light];
  button.addEventListener("click",()=>{state.light=button.dataset.light;document.querySelectorAll("[data-light]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));lightFeedback.textContent=lightTexts[state.light];saveState()});
});

// Pluralità regionale.
const regionData={
  france:{image:"assets/images/amiens-buttresses.webp",alt:"Archi rampanti e contrafforti del coro della cattedrale di Amiens",width:1800,height:1194,kicker:"Francia · XIII secolo",title:"Amiens: il sostegno si mostra",text:"L’altezza della navata e le grandi aperture dipendono da una rete esterna di archi rampanti e contrafforti. L’edificio non elimina la massa: la trasferisce e la rende leggibile anche nel profilo urbano.",caption:"Amiens: archi rampanti, contrafforti e coperture rendono visibile lo scheletro esterno del sistema.",data:[["Ritmo","verticale e serrato"],["Parete","progressivamente aperta"],["Città","cattedrale dominante"]]},
  england:{image:"assets/images/canterbury-choir.webp",alt:"Coro della cattedrale di Canterbury con archi, volte e lunga profondità prospettica",width:1800,height:1200,kicker:"Inghilterra · dal 1174",title:"Canterbury: profondità, memoria, pellegrinaggio",text:"Dopo l’incendio del 1174, il coro fu ricostruito con maestranze e soluzioni legate alla Francia, ma dentro un complesso che conserva parti romaniche e sviluppa una lunga articolazione orientale attorno al culto di Thomas Becket.",caption:"Canterbury: il coro gotico si innesta in una storia architettonica e liturgica più lunga.",data:[["Ritmo","orizzontale e profondo"],["Parete","stratificata nel tempo"],["Città","polo ecclesiastico e pellegrinaggio"]]},
  italy:{image:"assets/images/siena-interior.webp",alt:"Interno del Duomo di Siena con pilastri a fasce bianche e scure, archi e decorazione policroma",width:1800,height:1350,kicker:"Italia · XIII–XIV secolo",title:"Siena: struttura, policromia, comune",text:"Fasce di marmo, pareti ancora visivamente presenti, cupola, scultura e arredi producono una monumentalità diversa da Amiens. Materiali, tradizioni toscane, città comunale e cultura figurativa trasformano il linguaggio gotico.",caption:"Siena: il Gotico italiano unisce struttura, superficie policroma, scultura e identità civica.",data:[["Ritmo","alternanza policroma"],["Parete","presente e figurativa"],["Città","identità comunale"]]}
};
const regionImage=document.querySelector("#region-image");const regionKicker=document.querySelector("#region-kicker");const regionTitle=document.querySelector("#region-title");const regionText=document.querySelector("#region-text");const regionList=document.querySelector("#region-data");const dynamicZoom=document.querySelector(".dynamic-zoom");
function renderRegion(){const d=regionData[state.region];regionImage.src=d.image;regionImage.alt=d.alt;regionImage.width=d.width;regionImage.height=d.height;regionKicker.textContent=d.kicker;regionTitle.textContent=d.title;regionText.textContent=d.text;regionList.innerHTML=d.data.map(([term,value])=>`<div><dt>${term}</dt><dd>${value}</dd></div>`).join("");dynamicZoom.dataset.image=d.image;dynamicZoom.dataset.caption=d.caption;document.querySelectorAll("[data-region]").forEach(button=>button.setAttribute("aria-selected",String(button.dataset.region===state.region)))}
document.querySelectorAll("[data-region]").forEach(button=>button.addEventListener("click",()=>{state.region=button.dataset.region;saveState();renderRegion()}));renderRegion();

// Confronto Muro, struttura, luce.
const comparisonData={
  roman:{name:"Conques · Romanico",readings:{massa:"La massa muraria è immediatamente percepibile, ma non equivale a immobilità: campate, tribune e percorsi fanno muovere corpi e carichi.",sostegno:"Pilastri e pareti ricevono il peso delle volte; articolazioni e archi rendono leggibile il ritmo.",parete:"La parete delimita e sostiene, ospita immagini e produce zone di concentrazione.",apertura:"Le aperture sono calibrate rispetto a muratura, coperture e funzioni; non sono semplice mancanza di luce.",ritmo:"Campate e sostegni scandiscono il cammino verso transetto, deambulatorio e reliquie.",altezza:"L’elevazione esiste, ma si costruisce con rapporti più compatti e continuità muraria.",percorso:"Il pellegrino può raggiungere cappelle e reliquie dentro una circolazione organizzata.",luce:"La luce seleziona parti dello spazio e reagisce alla massa; il Romanico non è per definizione buio.",immagine:"Capitelli, portali e arredi entrano nel corpo architettonico.",liturgia:"Altari, coro, processioni e accessi differenziati regolano chi può stare dove.",citta:"L’abbazia lega il piccolo centro a reti di pellegrinaggio più vaste.",committenza:"Comunità monastica, doni e culto delle reliquie sostengono trasformazioni e prestigio.",lavoro:"Pietra, legno e volte richiedono cave, trasporti, centine e manutenzione.",potere:"L’autorità monastica organizza spazio, memoria, economia e accessi.",corpo:"Il visitatore avverte successione, limite, soglia e vicinanza materiale della pietra."}},
  french:{name:"Amiens · Gotico francese",readings:{massa:"La massa è spostata verso pilastri, contrafforti e archi rampanti; resta decisiva anche quando appare meno continua.",sostegno:"Una rete di elementi concentra e trasferisce carichi fino al terreno.",parete:"La parete alta può aprirsi perché parte della funzione resistente è affidata allo scheletro e ai sostegni esterni.",apertura:"Cleristorio e vetrate ampliano luce e immagine senza diventare elementi portanti principali.",ritmo:"Pilastri e costoloni guidano lo sguardo verso l’alto e lungo la navata.",altezza:"La scala nasce da tecnica, risorse, competizione e liturgia, non solo da aspirazione spirituale.",percorso:"Navata, coro, cappelle e portali organizzano assemblee e processioni su grande scala.",luce:"La luce colorata è costruita da aperture, vetro, piombo, orientamento e manutenzione.",immagine:"Scultura e vetrata occupano soglie e superfici, integrandosi all’architettura.",liturgia:"Lo spazio distingue laici, clero, coro e percorsi rituali.",citta:"Il profilo domina Amiens e rende visibili autorità episcopale e ambizione urbana.",committenza:"Capitolo, vescovo, donatori, fiscalità e mestieri sostengono campagne lunghe.",lavoro:"Specializzazioni numerose e coordinate costruiscono e riparano un sistema complesso.",potere:"La cattedrale rappresenta Chiesa e città, ma anche negoziazioni e disuguaglianze.",corpo:"L’altezza riduce la scala individuale e orienta insieme movimento, voce e sguardo."}},
  italian:{name:"Siena · Gotico italiano",readings:{massa:"La struttura convive con una forte percezione delle superfici e della policromia marmorea.",sostegno:"Pilastri, archi e volte organizzano lo spazio senza cercare la stessa dissoluzione muraria di Amiens.",parete:"La parete resta campo cromatico e figurativo, legato a tradizioni toscane e materiali locali.",apertura:"Finestre e oculi dialogano con ampie superfici decorate; l’equilibrio non replica il modello francese.",ritmo:"L’alternanza bianco-scura misura le campate e trasforma il sostegno in segno visivo.",altezza:"La verticalità è modulata da cupola, policromia, larghezza e rapporto con gli arredi.",percorso:"Pavimento, altari, pulpito e cappelle guidano un’esperienza fortemente figurativa.",luce:"La luce incontra marmo, pittura, scultura e vetrata; non domina da sola la percezione.",immagine:"Architettura e arti figurative restano inseparabili, preparando il nuovo problema dello spazio dipinto.",liturgia:"Cattedrale e riti si intrecciano con identità e calendario della città comunale.",citta:"Il Duomo partecipa alla competizione civica e al profilo monumentale di Siena.",committenza:"Opera del Duomo, comune, clero e donatori articolano decisioni e risorse.",lavoro:"Marmorari, scultori, pittori e costruttori rendono il cantiere un organismo plurale.",potere:"Devozione civica e istituzioni comunali non eliminano conflitti e differenze sociali.",corpo:"Il visitatore è avvolto da alternanze cromatiche, immagini e volumi più che da una sola tensione ascendente."}}
};
const comparisonCategories=["massa","sostegno","parete","apertura","ritmo","altezza","percorso","luce","immagine","liturgia","città","committenza","lavoro","potere","corpo"];
const categoryButtons=document.querySelector("#category-buttons");const comparisonReading=document.querySelector("#comparison-reading");
comparisonCategories.forEach(category=>{const button=document.createElement("button");button.type="button";button.dataset.category=category;button.textContent=category;button.addEventListener("click",()=>{state.comparison.category=category;saveState();renderComparison()});categoryButtons.append(button)});
function renderComparison(){document.querySelectorAll("[data-building]").forEach(button=>button.setAttribute("aria-selected",String(button.dataset.building===state.comparison.building)));categoryButtons.querySelectorAll("button").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.category===state.comparison.category)));comparisonReading.textContent=state.comparison.category?`${comparisonData[state.comparison.building].name} — ${comparisonData[state.comparison.building].readings[state.comparison.category]}`:"Scegli una categoria per mettere alla prova le differenze."}
document.querySelectorAll("[data-building]").forEach(button=>button.addEventListener("click",()=>{state.comparison.building=button.dataset.building;saveState();renderComparison()}));renderComparison();

// Verifica: ogni errore richiede un recupero differente e persistente.
const quizData=[
  {q:"Perché una cattedrale non può essere spiegata soltanto come espressione della fede?",options:["Perché è soprattutto una fortezza","Perché integra rito, tecnica, lavoro, finanza, istituzioni e conflitti","Perché il culto non vi svolge alcun ruolo"],correct:1,feedback:"La fede è decisiva, ma diventa edificio attraverso materiali, committenze, maestranze, economie e rapporti di potere.",link:"#dall-immagine",recovery:{q:"Quale catena rende materialmente possibile l’elevazione?",options:["Rivelazione senza lavoro","Cava, trasporto, taglio, sollevamento e manutenzione","Solo il disegno del vescovo"],correct:1}},
  {q:"Qual è il modo più corretto di descrivere l’Europa fra XI e XIII secolo?",options:["Un blocco immobile dopo Roma","Una crescita uniforme e pacifica","Trasformazioni diseguali, reti più dense e conflitti persistenti"],correct:2,feedback:"Produzione, popolazione, città e scambi crebbero con ritmi differenti e senza cancellare violenza e disuguaglianze.",link:"#europa",recovery:{q:"Perché “secoli bui” è una formula insufficiente?",options:["Nasconde trasformazioni e differenze regionali","Perché tutto fu luminoso","Perché Roma non ebbe alcuna eredità"],correct:0}},
  {q:"Che cosa indica con maggiore rigore la parola “Romanico”?",options:["Uno stile identico in tutta Europa","Una categoria moderna che riunisce esperienze regionali differenti","Il nome usato dagli architetti dell’XI secolo"],correct:1,feedback:"Romanico è una categoria storiografica: aiuta a confrontare, ma non cancella differenze di materiali, funzioni e regioni.",link:"#romanico",recovery:{q:"A Conques la forma risponde anche a…",options:["circolazione dei pellegrini e culto delle reliquie","rifiuto di ogni liturgia","una regola estetica europea immutabile"],correct:0}},
  {q:"Perché il portale romanico non è semplicemente una “Bibbia dei poveri”?",options:["Perché non contiene figure","Perché immagini, spazio, rito e autorità agiscono oltre la sola istruzione elementare","Perché era visibile soltanto ai monaci alfabetizzati"],correct:1,feedback:"Il portale poteva narrare, ammonire, impressionare, orientare e manifestare potere in relazione a parole e pratiche.",link:"#soglia",recovery:{q:"Quale azione il portale esercita direttamente sul corpo?",options:["Segna e organizza una soglia","Lo rende invisibile","Cancella la differenza fra dentro e fuori"],correct:0}},
  {q:"Quale affermazione sul cantiere medievale è fondata?",options:["Fu sempre opera spontanea di un popolo concorde","Dipese da committenze, professionalità, trasporti, fondi e negoziazioni","Ogni artefice rimase anonimo per scelta religiosa"],correct:1,feedback:"Il cantiere era un organismo economico e politico, con lavori specializzati, rischi, interruzioni e conflitti.",link:"#cantiere",recovery:{q:"Che cosa dimostra l’esistenza di maestri documentati?",options:["Che tutti firmavano","Che l’anonimato universale è un luogo comune","Che non esistevano botteghe"],correct:1}},
  {q:"Da che cosa deriva la verticalità di una grande cattedrale?",options:["Soltanto dal desiderio di avvicinarsi a Dio","Dall’incontro fra fede, tecnica, risorse, istituzioni, liturgia e competizione","Dall’assenza di costi"],correct:1,feedback:"L’aspirazione religiosa agisce attraverso possibilità tecniche e materiali e dentro una città che vuole essere vista.",link:"#citta",recovery:{q:"Quale effetto urbano può produrre la cattedrale?",options:["Modificare piazze, strade, economie e profilo","Scomparire dal profilo","Eliminare ogni concorrenza politica"],correct:0}},
  {q:"Qual è il ruolo storicamente più corretto di Suger?",options:["Unico inventore del Gotico","Committente e interprete decisivo di Saint-Denis, dentro innovazioni più ampie","Architetto di tutte le cattedrali francesi"],correct:1,feedback:"Saint-Denis è cruciale, ma le soluzioni avevano precedenti; la novità riguarda anche integrazione, scala e programma.",link:"#gotico",recovery:{q:"Il rapporto fra ogni forma gotica e una teologia della luce è…",options:["una certezza automatica","un problema storiografico da argomentare","privo di qualsiasi fonte o discussione"],correct:1}},
  {q:"Che cosa fa l’arco rampante nel sistema gotico?",options:["Elimina il peso della volta","Trasferisce spinte verso contrafforti esterni","Sostituisce ogni fondazione"],correct:1,feedback:"Il sistema redistribuisce i carichi. L’apparente leggerezza non è assenza di gravità.",link:"#solleva",recovery:{q:"Qual è la conclusione corretta?",options:["La pietra diventa priva di massa","Il peso viene organizzato perché lo spazio appaia più leggero","La vetrata sostiene da sola la volta"],correct:1}},
  {q:"Perché la vetrata non è semplice decorazione?",options:["Perché vetro, piombo, pittura, iconografia, committenza e liturgia trasformano luce e parete","Perché è scolpita nel marmo","Perché è sempre leggibile da vicino"],correct:0,feedback:"La vetrata è un oggetto materiale e sociale: filtra luce, organizza immagini e rende visibili donatori e mestieri.",link:"#luce",recovery:{q:"Quale materiale unisce i frammenti e partecipa al disegno?",options:["Piombo","Pergamena","Legno della centina"],correct:0}},
  {q:"Perché Canterbury è utile per capire il Gotico europeo?",options:["Perché copia senza variazioni Amiens","Perché un coro gotico si innesta in un complesso stratificato e in un centro di pellegrinaggio","Perché non conserva parti romaniche"],correct:1,feedback:"Il complesso mostra circolazione di maestranze, continuità e trasformazioni locali, non sostituzione totale.",link:"#pluralita",recovery:{q:"Romanico e Gotico nel tempo…",options:["possono coesistere e sovrapporsi","non si incontrano mai","sono separati da un anno preciso"],correct:0}},
  {q:"Come va interpretato il Gotico italiano?",options:["Come versione imperfetta di quello francese","Attraverso tradizioni murarie, materiali, ordini, città e culture figurative proprie","Come rifiuto assoluto di ogni innovazione gotica"],correct:1,feedback:"Siena mostra una combinazione storica autonoma di struttura, superficie, policromia, scultura e identità comunale.",link:"#pluralita",recovery:{q:"Quale tratto di Siena modifica il confronto con Amiens?",options:["Parete policroma e forte integrazione delle arti figurative","Assenza di città","Eliminazione di ogni arco"],correct:0}},
  {q:"In che modo il modulo 06 prepara Giotto?",options:["Dopo aver costruito un nuovo spazio architettonico, pone il problema di un corpo umano capace di abitare lo spazio rappresentato","Abbandona lo spazio per tornare ai simboli preistorici","Dimostra che pittura e architettura sono identiche"],correct:0,feedback:"L’architettura ha trasformato l’esperienza dello spazio; Giotto riporterà corpi, peso, azione e relazione dentro l’immagine.",link:"#confronto",recovery:{q:"Qual è la prossima domanda del percorso?",options:["Come l’uomo torna ad abitare lo spazio rappresentato","Come eliminare il corpo","Come rendere tutte le pareti uguali"],correct:0}}
];
const quizCard=document.querySelector("#quiz-card");const quizSummary=document.querySelector("#quiz-summary");const quizMeter=document.querySelector("#quiz-meter");const quizCount=document.querySelector("#quiz-count");
function persistQuiz(){saveState()}
function renderQuiz(){if(state.quiz.completed||state.quiz.index>=quizData.length)return renderSummary();if(state.quiz.pendingRecovery)return renderRecovery();const item=quizData[state.quiz.index];if(state.quiz.answeredCorrect)return renderCorrectState(item);quizCard.hidden=false;quizSummary.hidden=true;quizCard.className="quiz-card";quizCard.innerHTML=`<p class="question-no">${String(state.quiz.index+1).padStart(2,"0")}</p><h3>${item.q}</h3><div class="quiz-options"></div>`;const options=quizCard.querySelector(".quiz-options");item.options.forEach((text,index)=>{const button=document.createElement("button");button.type="button";button.textContent=text;button.addEventListener("click",()=>answerQuestion(index,button));options.append(button)});quizMeter.value=state.quiz.index;quizCount.textContent=`Domanda ${state.quiz.index+1} di ${quizData.length}`}
function renderCorrectState(item){quizCard.className="quiz-card";quizCard.innerHTML=`<p class="question-no">${String(state.quiz.index+1).padStart(2,"0")}</p><h3>${item.q}</h3><div class="quiz-feedback"><h4>Collegamento ricostruito</h4><p>${item.feedback}</p><div class="quiz-actions"><button type="button" id="quiz-next">Prosegui</button></div></div>`;quizCard.querySelector("#quiz-next").addEventListener("click",nextQuestion);quizMeter.value=state.quiz.index;quizCount.textContent=`Domanda ${state.quiz.index+1} di ${quizData.length}`}
function answerQuestion(index,button){const item=quizData[state.quiz.index];quizCard.querySelectorAll(".quiz-options button").forEach(option=>option.disabled=true);const correct=index===item.correct;button.classList.add(correct?"correct":"wrong");if(correct){state.quiz.direct+=1;state.quiz.answeredCorrect=true;quizCard.insertAdjacentHTML("beforeend",`<div class="quiz-feedback"><h4>Collegamento ricostruito</h4><p>${item.feedback}</p><div class="quiz-actions"><button type="button" id="quiz-next">Prosegui</button></div></div>`);quizCard.querySelector("#quiz-next").addEventListener("click",nextQuestion)}else{if(!state.quiz.errors.includes(state.quiz.index))state.quiz.errors.push(state.quiz.index);state.quiz.pendingRecovery=true;quizCard.insertAdjacentHTML("beforeend",`<div class="quiz-feedback"><h4>Il legame si è spezzato qui</h4><p>${item.feedback}</p><p><a href="${item.link}">Rivedi il passaggio pertinente</a>, poi affronta una domanda differente.</p><div class="quiz-actions"><button type="button" id="start-recovery">Avvia il recupero</button></div></div>`);quizCard.querySelector("#start-recovery").addEventListener("click",renderRecovery)}persistQuiz()}
function renderRecovery(){const item=quizData[state.quiz.index];quizCard.className="quiz-card recovery-card";quizMeter.value=state.quiz.index;quizCount.textContent=`Recupero della domanda ${state.quiz.index+1}`;if(state.quiz.recoveryPassed){quizCard.innerHTML=`<p class="recovery-label">Recupero completato</p><h3>${item.recovery.q}</h3><div class="quiz-feedback"><h4>Recupero riuscito</h4><p>Il nodo essenziale è di nuovo collegato. Puoi proseguire.</p><div class="quiz-actions"><button type="button" id="recovery-next">Prosegui</button></div></div>`;quizCard.querySelector("#recovery-next").addEventListener("click",nextQuestion);return}quizCard.innerHTML=`<p class="recovery-label">Recupero · domanda differente</p><h3>${item.recovery.q}</h3><div class="quiz-options"></div><div class="quiz-feedback" id="recovery-feedback"><p>La prosecuzione si sblocca quando il collegamento essenziale è ricostruito.</p></div>`;const options=quizCard.querySelector(".quiz-options");item.recovery.options.forEach((text,index)=>{const button=document.createElement("button");button.type="button";button.textContent=text;button.addEventListener("click",()=>{if(index===item.recovery.correct){options.querySelectorAll("button").forEach(option=>option.disabled=true);button.classList.add("correct");if(!state.quiz.recoveries.includes(state.quiz.index))state.quiz.recoveries.push(state.quiz.index);state.quiz.recoveryPassed=true;document.querySelector("#recovery-feedback").innerHTML=`<h4>Recupero riuscito</h4><p>Ora il nodo essenziale è di nuovo collegato. Puoi proseguire.</p><div class="quiz-actions"><button type="button" id="recovery-next">Prosegui</button></div>`;document.querySelector("#recovery-next").addEventListener("click",nextQuestion);persistQuiz()}else{button.classList.add("wrong");document.querySelector("#recovery-feedback").innerHTML=`<h4>Non ancora</h4><p>Cerca la relazione storica, non una formula assoluta. Prova un’altra risposta.</p>`}});options.append(button)})}
function nextQuestion(){state.quiz.index+=1;state.quiz.answeredCorrect=false;state.quiz.pendingRecovery=false;state.quiz.recoveryPassed=false;persistQuiz();renderQuiz();quizCard.scrollIntoView({block:"center",behavior:"smooth"})}
function renderSummary(){state.quiz.completed=true;persistQuiz();quizCard.hidden=true;quizSummary.hidden=false;quizMeter.value=quizData.length;quizCount.textContent="Percorso completato";const direct=state.quiz.direct;const recovered=state.quiz.recoveries.length;const unresolved=Math.max(0,state.quiz.errors.length-recovered);quizSummary.innerHTML=`<p class="question-no">Esito</p><h3>La struttura del ragionamento</h3><div class="summary-grid"><article><b>${direct}</b><span>corrette al primo tentativo</span></article><article><b>${recovered}</b><span>errori recuperati</span></article><article><b>${unresolved}</b><span>nodi ancora da rivedere</span></article></div><p>Il percorso non misura date isolate: verifica se sai collegare società, cantiere, struttura, luce e potere. I nodi irrisolti non possono essere zero per caso: ogni recupero è stato superato prima di procedere.</p><button type="button" id="quiz-restart">Ricomincia la verifica</button>`;quizSummary.querySelector("#quiz-restart").addEventListener("click",()=>{state.quiz=clone(defaultState.quiz);saveState();quizSummary.hidden=true;quizCard.hidden=false;renderQuiz()})}
renderQuiz();

// Visualizzatore accessibile: zoom, trascinamento, pinch, Escape e focus trap.
const lightbox=document.querySelector("#lightbox");const lightboxImage=document.querySelector("#lightbox-image");const lightboxCaption=document.querySelector("#lightbox-caption");const lightboxClose=document.querySelector("#lightbox-close");const zoomIn=document.querySelector("#zoom-in");const zoomOut=document.querySelector("#zoom-out");const zoomReset=document.querySelector("#zoom-reset");const lightboxStage=document.querySelector("#lightbox-stage");let lightboxReturnFocus=null;let scale=1;let panX=0;let panY=0;const pointers=new Map();let pinchDistance=0;let pinchScale=1;let dragStart=null;
function applyTransform(){lightboxImage.style.transform=`translate(${panX}px,${panY}px) scale(${scale})`;zoomReset.textContent=`${Math.round(scale*100)}%`}
function setScale(next){scale=Math.min(5,Math.max(1,next));if(scale===1){panX=0;panY=0}applyTransform()}
function openLightbox(button){lightboxReturnFocus=button;lightboxImage.src=button.dataset.image;lightboxImage.alt=button.dataset.caption||"Opera ingrandita";lightboxCaption.textContent=button.dataset.caption||"";lightbox.hidden=false;document.body.classList.add("dialog-open");scale=1;panX=0;panY=0;applyTransform();lightboxClose.focus()}
function closeLightbox(){lightbox.hidden=true;lightboxImage.src="";document.body.classList.remove("dialog-open");pointers.clear();lightboxReturnFocus?.focus()}
document.querySelectorAll(".zoom-open").forEach(button=>button.addEventListener("click",()=>openLightbox(button)));lightboxClose.addEventListener("click",closeLightbox);zoomIn.addEventListener("click",()=>setScale(scale+.25));zoomOut.addEventListener("click",()=>setScale(scale-.25));zoomReset.addEventListener("click",()=>{scale=1;panX=0;panY=0;applyTransform()});
lightboxStage.addEventListener("wheel",event=>{event.preventDefault();setScale(scale+(event.deltaY<0?.2:-.2))},{passive:false});
function distanceBetweenPointers(){const[a,b]=[...pointers.values()];return a&&b?Math.hypot(a.x-b.x,a.y-b.y):0}
lightboxStage.addEventListener("pointerdown",event=>{lightboxStage.setPointerCapture?.(event.pointerId);pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2){pinchDistance=distanceBetweenPointers();pinchScale=scale;dragStart=null}else if(pointers.size===1&&scale>1){dragStart={x:event.clientX,y:event.clientY,panX,panY}}});
lightboxStage.addEventListener("pointermove",event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2){const nextDistance=distanceBetweenPointers();if(pinchDistance)setScale(pinchScale*nextDistance/pinchDistance)}else if(dragStart&&scale>1){panX=dragStart.panX+event.clientX-dragStart.x;panY=dragStart.panY+event.clientY-dragStart.y;applyTransform()}});
function endPointer(event){pointers.delete(event.pointerId);dragStart=null;if(pointers.size<2)pinchDistance=0}lightboxStage.addEventListener("pointerup",endPointer);lightboxStage.addEventListener("pointercancel",endPointer);
document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(!lightbox.hidden)closeLightbox();else if(!nav.hidden)closeNav();return}if(event.key==="Tab"&&!lightbox.hidden){const focusables=[...lightbox.querySelectorAll("button:not([disabled])")];const first=focusables[0];const last=focusables.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});

if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(error=>console.warn("Service Worker non registrato:",error)));
