import {works,steps} from './content.js';
import {videos} from './videos.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='gbprof-david-goya-v1';
let state={notes:{},choices:{},seen:[],answers:{},step:0},storageOK=true;
try{const data=JSON.parse(localStorage.getItem(KEY));if(data&&typeof data==='object')state={...state,...data};}catch{storageOK=false;}
if(!Array.isArray(state.seen))state.seen=[];
let current=Number.isInteger(state.step)?Math.min(7,Math.max(0,state.step)):0, showSpots=false, mobileWork='david', detail;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;$('#storage-status').textContent='Il browser non consente il salvataggio. Scarica il taccuino prima di chiudere.';}}
function shuffle(a){return [...a].sort(()=>Math.random()-.5);}
function el(tag,props={},text){const e=document.createElement(tag);Object.assign(e,props);if(text!==undefined)e.textContent=text;return e;}
class Viewer{
 constructor(key){this.key=key;this.work=works[key];this.z=1;this.tx=0;this.ty=0;this.points=new Map();this.chosen=null;
  this.root=el('article',{className:'viewer'});this.root.dataset.work=key;
  this.root.innerHTML=`<div class="viewer-head"><h4>${this.work.name}</h4><span>${this.work.date}</span></div><div class="stage" tabindex="0" role="group" aria-label="Esplora ${this.work.title}: frecce, più, meno e zero"><div class="scene"><img draggable="false" src="${this.work.src}" alt="${this.work.alt}"><div class="highlight" hidden></div></div></div><div class="viewer-tools"><button data-action="minus" aria-label="Riduci ${key}">−</button><button data-action="plus" aria-label="Ingrandisci ${key}">+</button><button data-action="reset" aria-label="Opera completa ${key}">Intero</button><output aria-label="Livello di zoom ${key}">100%</output></div><label class="sr-only" for="spots-${key}">Dettaglio da esplorare in ${key}</label><select class="spot-select" id="spots-${key}"><option value="">Esplora un dettaglio…</option></select><p class="spot-description" aria-live="polite">${this.work.title}. Scegli un dettaglio oppure osserva liberamente.</p>`;
  $('#viewers').append(this.root);this.stage=this.root.querySelector('.stage');this.scene=this.root.querySelector('.scene');this.highlight=this.root.querySelector('.highlight');this.description=this.root.querySelector('.spot-description');this.select=this.root.querySelector('select');this.output=this.root.querySelector('output');this.buttons=[];
  this.work.spots.forEach((s,i)=>{this.select.add(new Option(s[1],s[0]));const b=el('button',{className:'spot',hidden:true});b.setAttribute('aria-label',`${s[1]} — ${this.work.name}`);b.innerHTML=`<span>${i+1}</span>`;b.addEventListener('click',()=>this.focus(s[0]));this.stage.append(b);this.buttons.push(b);});
  this.select.addEventListener('change',()=>this.select.value?this.focus(this.select.value):this.reset());
  this.root.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>b.dataset.action==='reset'?this.reset():this.zoom(this.z*(b.dataset.action==='plus'?1.4:1/1.4))));
  this.stage.addEventListener('keydown',e=>{if(e.target!==this.stage)return;const moves={ArrowLeft:[45,0],ArrowRight:[-45,0],ArrowUp:[0,45],ArrowDown:[0,-45]};if(moves[e.key]){e.preventDefault();this.tx+=moves[e.key][0];this.ty+=moves[e.key][1];this.draw();}else if(['+','=','-','0'].includes(e.key)){e.preventDefault();if(e.key==='0')this.reset();else this.zoom(this.z*(e.key==='-'?1/1.4:1.4));}});
  this.stage.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();this.zoom(this.z*Math.exp(-e.deltaY*.006));},{passive:false});
  this.stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;this.stage.setPointerCapture(e.pointerId);this.points.set(e.pointerId,{x:e.clientX,y:e.clientY});});
  this.stage.addEventListener('pointermove',e=>{if(!this.points.has(e.pointerId))return;const old=[...this.points.values()],last=this.points.get(e.pointerId);this.points.set(e.pointerId,{x:e.clientX,y:e.clientY});const now=[...this.points.values()];if(now.length===2){const dist=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(dist(old)>0)this.zoom(this.z*dist(now)/dist(old));}else{this.tx+=e.clientX-last.x;this.ty+=e.clientY-last.y;this.draw();}});
  ['pointerup','pointercancel','lostpointercapture'].forEach(type=>this.stage.addEventListener(type,e=>this.points.delete(e.pointerId)));
  new ResizeObserver(()=>{if(this.stage.clientWidth){this.fit();if(this.chosen)this.focus(this.chosen);else this.reset();}}).observe(this.stage);this.fit();this.reset();
 }
 fit(){this.w=this.stage.clientWidth||400;this.h=this.stage.clientHeight||490;this.base=Math.min(this.w/this.work.w,this.h/this.work.h);this.iw=this.work.w*this.base;this.ih=this.work.h*this.base;this.scene.style.width=this.iw+'px';this.scene.style.height=this.ih+'px';}
 draw(){const w=this.iw*this.z,h=this.ih*this.z;this.tx=w<=this.w?(this.w-w)/2:Math.max(this.w-w,Math.min(0,this.tx));this.ty=h<=this.h?(this.h-h)/2:Math.max(this.h-h,Math.min(0,this.ty));this.scene.style.transform=`translate(${this.tx}px,${this.ty}px) scale(${this.z})`;this.output.textContent=Math.round(this.z*100)+'%';this.buttons.forEach((b,i)=>{const s=this.work.spots[i],x=this.tx+s[2]*w,y=this.ty+s[3]*h;b.style.left=x+'px';b.style.top=y+'px';b.hidden=!showSpots||x<10||x>this.w-10||y<10||y>this.h-10;});}
 zoom(z){const prev=this.z;this.z=Math.max(1,Math.min(8,z));this.tx=this.w/2-(this.w/2-this.tx)*(this.z/prev);this.ty=this.h/2-(this.h/2-this.ty)*(this.z/prev);this.draw();}
 reset(){this.chosen=null;this.z=1;this.tx=0;this.ty=0;this.highlight.hidden=true;this.select.value='';this.description.textContent=this.work.title+'. Scegli un dettaglio oppure osserva liberamente.';this.draw();}
 focus(id){const s=this.work.spots.find(s=>s[0]===id);if(!s)return;this.chosen=id;this.z=Math.max(1,Math.min(8,Math.min(this.w/(s[4]*this.iw),this.h/(s[5]*this.ih))*.72));this.tx=this.w/2-s[2]*this.iw*this.z;this.ty=this.h/2-s[3]*this.ih*this.z;Object.assign(this.highlight.style,{left:(s[2]-s[4]/2)*100+'%',top:(s[3]-s[5]/2)*100+'%',width:s[4]*100+'%',height:s[5]*100+'%',borderWidth:2/this.z+'px'});this.highlight.hidden=false;this.select.value=id;this.description.textContent=s[1]+'. '+s[6];this.draw();}
}
const viewers={david:new Viewer('david'),goya:new Viewer('goya')};
function switchWork(k){mobileWork=k;$$('.mobile-switch button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.work===k));Object.entries(viewers).forEach(([key,v])=>v.root.classList.toggle('mobile-hidden',key!==k));}
switchWork('david');$$('.mobile-switch button').forEach(b=>b.addEventListener('click',()=>switchWork(b.dataset.work)));
$('#focus-pair').addEventListener('click',()=>{const p=steps[current].pair;viewers.david.focus(p[0]);viewers.goya.focus(p[1]);});
$('#reset-pair').addEventListener('click',()=>Object.values(viewers).forEach(v=>v.reset()));
$('#toggle-spots').addEventListener('click',e=>{showSpots=!showSpots;e.currentTarget.setAttribute('aria-pressed',showSpots);e.currentTarget.textContent=showSpots?'Nascondi i punti di osservazione':'Mostra i punti di osservazione';Object.values(viewers).forEach(v=>v.draw());});
steps.forEach((s,i)=>{const b=el('button',{},String(i+1).padStart(2,'0')+' '+s.title);b.addEventListener('click',()=>renderStep(i,true));$('#steps').append(b);});
function progress(){const n=steps.filter(s=>state.seen.includes(s.id)).length;$('#progress').textContent=n+' di 8 confronti esplorati';$$('#steps button').forEach((b,i)=>b.classList.toggle('done',state.seen.includes(steps[i].id)));$('#theory').hidden=n<8;$('#theory-lock').hidden=n===8;}
function videoBlock(n,target){
 const v=videos[n];if(!v)return;
 const fullAvailable=steps.every(s=>state.seen.includes(s.id));
 const clip=v.clip&&!fullAvailable?v.clip:null;
 const wrap=el('details',{className:'video-block'});
 wrap.append(el('summary',{},(clip?clip.title:v.title)+' · '+(clip?clip.duration:v.duration)));
 wrap.append(el('p',{className:'video-note'},clip?'Estratto dal video originale: osserva il dettaglio e confrontalo con la lettura proposta. Il video completo, con le precisazioni, sarà disponibile dopo gli otto confronti.':v.note));
 const btn=el('button',{},'Carica il video');wrap.append(btn);
 btn.addEventListener('click',()=>{
  const player=el('video',{controls:true,preload:'none',poster:`assets/video/poster-${n}.jpg`});
  player.setAttribute('playsinline','');player.setAttribute('aria-label',clip?clip.title:v.title);
  player.src='assets/video/'+(clip?clip.src:`video-${n}.mp4`);
  const track=el('track',{kind:'captions',srclang:'it',label:'Italiano',src:'assets/video/'+(clip?clip.captions:`video-${n}.vtt`)});player.append(track);btn.replaceWith(player);
 });
 const transcript=clip?clip.text:v.text;
 if(transcript){const t=el('details',{className:'transcript'});t.append(el('summary',{},clip?'Leggi il contenuto dell’estratto':'Leggi la trascrizione del video'));t.append(el('p',{},transcript));wrap.append(t);}
 target.append(wrap);
}
function renderStep(i,focus=false){$$('video').forEach(v=>v.pause());current=i;state.step=i;save();const s=steps[i];$$('#steps button').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-current',i===j?'step':'false');});$('#step-number').textContent='CONFRONTO '+String(i+1).padStart(2,'0')+' / 08';$('#step-title').textContent=s.title;$('#step-subtitle').textContent=s.subtitle;$('#question').textContent=s.question;$('#choices').replaceChildren(el('legend',{className:'sr-only'},'Scegli un’ipotesi'));
 shuffle(s.choices.map((text,j)=>({text,j}))).forEach(c=>{const label=el('label'),input=el('input',{type:'radio',name:'hypothesis',value:String(c.j),checked:state.choices[s.id]===c.j});label.append(input,el('span',{},c.text));input.addEventListener('change',()=>{state.choices[s.id]=c.j;save();});$('#choices').append(label);});
 $('#note').value=state.notes[s.id]||'';$('#feedback').textContent='';$('#interpretation').hidden=!state.seen.includes(s.id);$('#reading-david').textContent=s.david;$('#reading-goya').textContent=s.goya;$('#relation').textContent=s.relation;$('#video-slot').replaceChildren();Object.entries(videos).filter(([n,v])=>v.step===s.id).forEach(([n])=>videoBlock(n,$('#video-slot')));$('#next').textContent=i===7?'Dai un nome alle differenze →':'Il prossimo confronto →';Object.values(viewers).forEach(v=>v.reset());progress();if(focus)$('#step-title').focus();}
$('#note').addEventListener('input',e=>{state.notes[steps[current].id]=e.target.value;save();});
$('#reveal').addEventListener('click',()=>{const s=steps[current],choice=state.choices[s.id];if(choice===undefined){$('#feedback').textContent='Scegli prima un’ipotesi: serve a confrontare la tua lettura con gli indizi.';return;}$('#feedback').textContent=choice===s.best?'L’ipotesi è sostenuta da questi indizi. Leggi il confronto e verifica la tua osservazione.':'Riguarda un dettaglio: '+s.recovery;$('#interpretation').hidden=false;if(!state.seen.includes(s.id))state.seen.push(s.id);save();progress();});
$('#next').addEventListener('click',()=>{if(current<7){renderStep(current+1,true);$('#lab-title').scrollIntoView();}else location.hash='conclusione';});
[['Passato: morte avvenuta','cadaveri'],['Presente: morte imminente','uomo'],['Futuro: chi attende','attesa']].forEach(([name,answer],i)=>{const box=el('div'),label=el('label',{htmlFor:'time-'+i},name),select=el('select',{id:'time-'+i});select.dataset.answer=answer;select.add(new Option('Associa un gruppo…',''));shuffle([['uomo','L’uomo con la camicia bianca'],['attesa','Il gruppo dietro l’uomo'],['cadaveri','I corpi in primo piano']]).forEach(([value,text])=>select.add(new Option(text,value)));select.addEventListener('change',()=>{if(select.value){switchWork('goya');viewers.goya.focus(select.value);}});box.append(label,select);$('.time-fields').append(box);});
$('#check-time').addEventListener('click',()=>{const a=$$('.time-fields select');const count=a.filter(s=>s.value===s.dataset.answer).length;$('#time-feedback').textContent=count===3?'3 su 3. La tela connette tre fasi della stessa violenza. Ricorda: tutti questi gruppi sono dipinti insieme nel 1814.':`${count} su 3. Riguarda: i corpi a terra mostrano il già avvenuto; l’uomo in bianco la morte imminente; chi avanza dietro di lui ciò che accadrà. Riprova le associazioni.`;});
function newDetail(){const options=[['david','lettera'],['david','cassa'],['david','ferita'],['goya','lanterna'],['goya','fucili'],['goya','mani']].filter(x=>!detail||x.join('/')!==detail.join('/'));detail=options[Math.floor(Math.random()*options.length)];const w=works[detail[0]],s=w.spots.find(s=>s[0]===detail[1]),box=$('#detail-image');const bw=box.clientWidth||330,bh=box.clientHeight||290,scale=Math.max(bw/(s[4]*w.w*1.6),bh/(s[5]*w.h*1.6));box.style.backgroundImage=`url('${w.src}')`;box.style.backgroundSize=`${w.w*scale}px ${w.h*scale}px`;box.style.backgroundPosition=`${bw/2-s[2]*w.w*scale}px ${bh/2-s[3]*w.h*scale}px`;box.setAttribute('aria-label','Dettaglio da riconoscere: '+s[1].toLowerCase()+', ingrandito senza il resto dell’opera.');$('#recognize-work').value='';$('#detail-feedback').textContent='';}
$('#new-detail').addEventListener('click',newDetail);
$('#check-detail').addEventListener('click',()=>{if(!$('#recognize-work').value){$('#detail-feedback').textContent='Scegli prima l’opera e prova a motivare.';return;}const w=works[detail[0]],s=w.spots.find(s=>s[0]===detail[1]);$('#detail-feedback').textContent=($('#recognize-work').value===detail[0]?'Opera riconosciuta. ':'Il dettaglio appartiene a '+w.title+'. ')+s[6]+' Confronta questa lettura con la tua motivazione: il testo aperto non è valutato automaticamente.';});
$$('[data-save]').forEach(t=>{t.value=state.answers[t.id]||'';t.addEventListener('input',()=>{state.answers[t.id]=t.value;save();});});
$('#export-notes').addEventListener('click',()=>{const lines=['DAVID E GOYA — IL MIO TACCUINO','',...steps.flatMap(s=>[s.title,`Ipotesi: ${s.choices[state.choices[s.id]]||'Non scelta'}`,state.notes[s.id]||'(Nessuna nota)','']),...Object.entries(state.answers).flatMap(([k,v])=>[k,v,''])];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=el('a',{href:url,download:'David-Goya-taccuino.txt'});a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);});
$('#clear-notes').addEventListener('click',()=>{if(!confirm('Cancellare risposte e progressi di questo laboratorio dal dispositivo?'))return;state={notes:{},choices:{},seen:[],answers:{},step:0};save();$$('[data-save]').forEach(t=>t.value='');renderStep(0);$('#storage-status').textContent='Risposte e progressi cancellati.';});
Object.entries(videos).filter(([n,v])=>v.step==='finale').forEach(([n])=>videoBlock(n,$('#final-video')));
renderStep(current);newDetail();if(!storageOK)$('#storage-status').textContent='Il salvataggio nel browser non è disponibile: scarica il taccuino prima di chiudere.';
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>$('#offline-status').textContent='Opere, percorso e attività pronti per la lettura offline. Video e collegamenti esterni richiedono la rete.').catch(()=>$('#offline-status').textContent='Salvataggio offline non riuscito. Riapri il laboratorio con una connessione disponibile.');}else $('#offline-status').textContent='Questo browser non supporta la lettura offline della PWA.';
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false;});$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true;}});
