/* Coordinate normalizzate sulle copie originali Drive: David 960×1235; Goya 1920×1480. */
export const works = {
 david:{name:'Jacques-Louis David',title:'La morte di Marat',date:'1793',src:'assets/images/david.jpg',w:960,h:1235,alt:'Marat morto nella vasca: testa reclinata, lettera nella mano, braccio abbandonato, coltello a terra e cassa con dedica, davanti a un fondo oscuro.',spots:[
 ['volto','Volto',.177,.482,.16,.16,'Gli occhi sono chiusi. Il volto non ci permette di ricostruire le emozioni reali di Marat: ci mostra come David vuole ricordarlo.'],
 ['ferita','Ferita',.272,.574,.105,.13,'Una piccola ferita sul torace, una traccia di sangue: l’assassinio non è cancellato, ma ricondotto a una forma controllata.'],
 ['braccio','Braccio',.337,.813,.30,.30,'Il braccio ricade verso il pavimento. L’abbandono del corpo richiama anche la tradizione delle immagini del Cristo morto.'],
 ['lettera','Lettera',.759,.571,.20,.12,'La lettera introduce nella scena Charlotte Corday, anche se il suo corpo è assente. Il testo dipinto partecipa alla costruzione della vittima.'],
 ['coltello','Coltello',.196,.972,.23,.055,'Il coltello insanguinato giace sul pavimento: chi ha colpito è fuori campo, l’arma resta.'],
 ['cassa','Cassa',.731,.826,.31,.32,'La cassa modesta sostiene gli strumenti di scrittura e reca la dedica «À Marat, David». Un oggetto quotidiano assume la forza di un monumento.'],
 ['fondo','Fondo scuro',.54,.23,.75,.35,'L’ampia superficie oscura sottrae dettagli all’ambiente e concentra l’attenzione sulla figura.'],
 ['corpo','Corpo',.375,.685,.66,.56,'Un solo corpo domina. La posa è costruita con cura, non registrata come in un sopralluogo.']
 ]},
 goya:{name:'Francisco Goya',title:'Il 3 maggio 1808',date:'1814',src:'assets/images/goya.jpg',w:1920,h:1480,alt:'Un uomo in camicia bianca alza le braccia davanti a un plotone francese. A terra ci sono cadaveri e sangue; altri uomini attendono. Una lanterna illumina le vittime e Madrid resta in ombra.',spots:[
 ['uomo','Uomo in bianco',.319,.563,.22,.40,'La camicia bianca attira lo sguardo. L’uomo è ancora vivo, esposto ai fucili e privo di un’arma visibile.'],
 ['volto','Volto',.335,.451,.085,.11,'Gli occhi aperti e la bocca dischiusa rendono visibile una reazione alla morte imminente. Non conosciamo l’identità dell’uomo.'],
 ['mani','Mani',.314,.399,.24,.09,'Le mani sollevate rendono il corpo vulnerabile. Il gesto può suggerire protesta, paura e un richiamo alla crocifissione: non ha un solo significato.'],
 ['soldati','Soldati',.777,.65,.42,.56,'Uniformi, schiene, gambe e armi si ripetono. Non sono privi di corpi: è la loro individualità a diventare poco riconoscibile.'],
 ['fucili','Fucili',.566,.507,.30,.09,'Le canne parallele dirigono la violenza contro le vittime. La composizione rende coordinata l’azione del plotone.'],
 ['lanterna','Lanterna',.62,.742,.105,.16,'La sorgente di luce è dentro la scena. Rende le vittime visibili, ma non le salva.'],
 ['cadaveri','Cadaveri',.211,.832,.40,.21,'I corpi già colpiti occupano il primo piano: ciò che è accaduto anticipa il destino dei vivi.'],
 ['sangue','Sangue',.302,.782,.25,.08,'Il sangue si distende sul terreno: la morte ha peso, materia e conseguenze fisiche.'],
 ['attesa','Gruppo in attesa',.50,.635,.19,.32,'Dietro l’uomo in bianco altri condannati avanzano o si coprono il volto. Il loro futuro si legge nei morti davanti a loro.'],
 ['citta','Città',.624,.306,.39,.24,'Gli edifici collocano la scena nella storia e nello spazio urbano, senza trasformare il quadro in una fotografia topografica.']
 ]}
};
export const steps=[
 {id:'corpo',title:'Il corpo',subtitle:'Uno. Molti.',question:'Dove si ferma il tuo sguardo? Su una figura isolata o su una successione di corpi?',pair:['corpo','uomo'],choices:['In entrambi i quadri un solo corpo esaurisce il racconto.','In David il corpo è isolato; in Goya entra in una sequenza.','In Goya conta soltanto il numero delle figure.'],best:1,
 david:'Marat è separato dal disordine dell’assassinio. Il corpo, modellato dalla luce, ha una consistenza quasi scultorea. La scena ci invita a fermarci su una figura che diventa esemplare.',
 goya:'L’uomo in bianco non è solo. I morti davanti a lui e i vivi accanto e dietro costruiscono un destino comune. Il corpo individuale appartiene a una storia collettiva.',
 relation:'Isolare e moltiplicare sono scelte compositive. David concentra la memoria su Marat; Goya mette una figura in relazione con altri esseri umani. Anche l’uomo in bianco, però, può diventare un simbolo.',
 recovery:'Ritorna alla visione completa: segui la sagoma di Marat, poi conta i diversi gruppi di Goya. Non basta contare: chiediti come sono collegati.'},
 {id:'ferita',title:'La ferita e il sangue',subtitle:'La traccia. La materia.',question:'La violenza scompare quando viene mostrata con misura?',pair:['ferita','sangue'],choices:['La ferita contenuta rende meno reale l’assassinio.','Il sangue abbondante garantisce un racconto oggettivo.','Entrambe le opere mostrano violenza, trasformandola diversamente.'],best:2,
 david:'La ferita è piccola ma leggibile, e il sangue compare anche sul tessuto. David non cancella il delitto: ne controlla la visibilità, senza lasciare che il trauma disgreghi la figura.',
 goya:'Le macchie sul terreno e i corpi riversi fanno incontrare la morte nella sua dimensione fisica. Il primo piano impedisce di osservare l’esecuzione da una distanza rassicurante.',
 relation:'Non confrontiamo una morte pacifica e una morte violenta: entrambe sono violente. Confrontiamo due modi di rappresentarne le conseguenze. Più sangue non significa automaticamente più verità.',
 recovery:'Osserva la ferita e il panno in David, poi il terreno in Goya. Distingui la presenza della violenza dalla quantità di spazio che il pittore le assegna.'},
 {id:'volto',title:'Il volto',subtitle:'Occhi chiusi. Occhi aperti.',question:'I due volti appartengono allo stesso momento rispetto alla morte?',pair:['volto','volto'],choices:['Marat è già morto; l’uomo in bianco vive l’attesa.','Entrambi i volti mostrano l’istante in cui si viene colpiti.','La differenza dipende solo dal carattere dei due uomini.'],best:0,
 david:'Gli occhi chiusi e il capo reclinato appartengono al dopo. L’assenza di terrore visibile non dimostra che Marat abbia accolto serenamente la morte: è il risultato dell’immagine costruita da David.',
 goya:'L’uomo guarda verso il plotone. Occhi, bocca e braccia rendono leggibile una tensione ancora in atto: non è un ritratto postumo, ma una vita davanti alla propria fine.',
 relation:'Prima di attribuire emozioni o ideologie, riconosci il tempo rappresentato. Il volto di un morto e quello di chi sta per morire non sono due risposte psicologiche a una situazione identica.',
 recovery:'Chiediti prima «è ancora vivo?». Poi cerca gli indizi visibili, senza trasformarli in certezze sulle emozioni reali.'},
 {id:'chi-uccide',title:'Chi uccide?',subtitle:'Assente. Senza volto.',question:'Perché David lascia Charlotte Corday fuori dalla scena, mentre Goya mostra il plotone?',pair:['coltello','soldati'],choices:['David non conosce l’assassina; Goya conosce i soldati.','L’assenza e l’anonimato orientano diversamente lo sguardo.','L’assenza di Corday elimina il significato politico dell’opera.'],best:1,
 david:'Charlotte Corday è un individuo storico, ma non compare. La lettera, la ferita e l’arma ne attestano l’azione. Il confronto tra due persone viene sottratto allo sguardo: resta la centralità del martire rivoluzionario.',
 goya:'I soldati sono presenti, ma schiene e uniformi nascondono quasi tutti i tratti individuali. La ripetizione dei fucili li unisce in un dispositivo di esecuzione. La violenza appare organizzata.',
 relation:'In David l’assassina è identificabile ma assente; in Goya gli esecutori sono visibili ma difficili da distinguere. È una lettura degli effetti della composizione, non una dichiarazione documentata di ogni intenzione dei pittori.',
 recovery:'Cerca le tracce di Corday in David. Poi prova a descrivere un singolo soldato di Goya senza usare l’uniforme: la difficoltà è parte dell’effetto del quadro.'},
 {id:'spazio',title:'Lo spazio',subtitle:'Togliere. Collegare.',question:'Che cosa cambia quando lo sfondo non ci racconta quasi nulla?',pair:['fondo','citta'],choices:['Uno sfondo essenziale rende il dipinto privo di storia.','Molte figure rendono impossibile un ordine compositivo.','La selezione e la densità narrativa guidano l’attenzione.'],best:2,
 david:'Il grande fondo oscuro contiene pochissimi riferimenti. Restano vasca, tessuti, strumenti di scrittura e cassa. L’ambiente domestico viene selezionato per costruire una memoria concentrata.',
 goya:'Collina, città, luce, soldati e condannati formano relazioni spaziali. Il primo piano dei morti, il gruppo centrale e il fondo urbano danno profondità al racconto.',
 relation:'Sottrazione e accumulazione narrativa non equivalgono a ordine contro disordine. Anche Goya organizza rigorosamente la scena: la direzione dei fucili lo mostra bene.',
 recovery:'Osserva lo sfondo senza i protagonisti. Poi segui una linea compositiva: il bordo della vasca, oppure la direzione dei fucili.'},
 {id:'luce',title:'La luce',subtitle:'Rivelare non è salvare.',question:'La luce rende il mondo più razionale, o può rendere visibile anche la sua violenza?',pair:['corpo','lanterna'],choices:['In David modella una figura; in Goya espone le vittime.','La luce serve soltanto a indicare l’ora degli eventi.','In entrambe le opere dimostra che la ragione vince.'],best:0,
 david:'Una luce direzionata modella il torace e il volto, staccandoli dal fondo. La figura acquista evidenza e dignità monumentale: è resa degna di memoria.',
 goya:'La lanterna è un oggetto della scena. Illumina le vittime e la camicia bianca; il plotone resta più oscuro. Vedere con chiarezza non impedisce l’uccisione.',
 relation:'Il rapporto tra luce e ragione può diventare una domanda storica, non un codice automatico. Rivoluzione e conquiste napoleoniche mostrano tensioni tra emancipazione e dominio. Goya, vicino alla cultura dei Lumi, non si riduce a un rifiuto della ragione.',
 recovery:'Individua la sorgente luminosa visibile in Goya. In David osserva invece gli effetti sul corpo. Separa la luce dipinta dalla metafora della ragione.'},
 {id:'gesto',title:'Il gesto',subtitle:'Abbandono. Esposizione.',question:'Come cambia il significato di un corpo quando le braccia ricadono oppure si aprono?',pair:['braccio','mani'],choices:['Le pose sono gesti spontanei senza funzione espressiva.','Entrambi i gesti mostrano un identico stato del corpo.','Le pose costruiscono immobilità, vulnerabilità e richiami simbolici.'],best:2,
 david:'Il braccio abbandonato accompagna lo sguardo verso il basso. La mano conserva la penna: il lavoro politico entra nella memoria del morto. La posa può richiamare modelli di compianto cristiano.',
 goya:'Le braccia aperte espongono l’uomo. Altri si coprono il volto, pregano o si ripiegano. Il richiamo alla crocifissione è possibile, ma non annulla la concreta condizione di un condannato.',
 relation:'Il simbolo non appartiene soltanto a David. Anche Goya attinge a gesti carichi di memoria culturale. Il confronto diventa più interessante quando le differenze non cancellano i punti di contatto.',
 recovery:'Guarda mani e braccia di più figure. Distingui la posa visibile dalle interpretazioni possibili: una mano alzata non significa necessariamente una sola cosa.'},
 {id:'tempo',title:'Il tempo',subtitle:'Un istante. Tre destini.',question:'Può un’immagine immobile raccontare ciò che è avvenuto e ciò che deve ancora accadere?',pair:['corpo','attesa'],choices:['Goya mette in relazione morti, condannato e gruppo in attesa.','Un quadro può mostrare soltanto un presente senza relazioni.','David e Goya dipingono direttamente durante gli avvenimenti.'],best:0,
 david:'Il delitto è già avvenuto. Coltello e lettera rimandano a un prima che non vediamo; la dedica sulla cassa apre alla memoria futura. Il quadro concentra queste relazioni in una presenza immobile.',
 goya:'I cadaveri indicano ciò che è già successo; l’uomo in bianco affronta il momento imminente; gli altri condannati attendono. Passato, presente e futuro sono un modo di leggere gruppi compresenti.',
 relation:'1808 è la data degli eventi; 1814 è la data della tela. Sei anni separano i due momenti. Anche Goya seleziona e ricostruisce: nessuna delle due opere è una registrazione neutrale.',
 recovery:'Distingui due tempi: quello raccontato dentro il dipinto e quello in cui il pittore lo realizza. Poi associa i tre gruppi di Goya alla sequenza della morte.'}
];
